name: Deploy to github.io

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - name: npm install, lint
      run: |
        npm install -f
        npm run lint:fix
        npm run build
      
    - name: Deploy to github.io
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: build
